Ext.define('MyApp.view.login.LoginController',{
    extend:'Ext.app.ViewController',
    alias:'controller.login',
    onLoginClick:function(){
        localStorage.setItem('LoginStatus',true);
        this.getView().destroy();
        Ext.ViewPort.setActiveItem(Ext.create({
            xtype:'app-main'
        }));
    },
    onCancelClick:function(){
        this.getView().hide();
    }
});